Create copilot-svc-deployment workflow
graticule-life/reusable-workflow pull request #3
Opened 2023-11-27 21:45 UTC by bathsundeep-graticule

2023-11-28 04:37 UTC, mygzi commented on .github/workflows/ghcr-ecr-republish.yml
> +      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
This is new (to me) bash syntax!

2023-11-28 04:59 UTC, mygzi requested changes

2023-11-28 04:59 UTC, mygzi commented on .github/workflows/copilot-svc-deploy.yml
> +      uses: ksivamuthu/aws-copilot-github-action@v0.0.7
Need to pin the copilot version being installed/used - `version:` should do it

2023-11-28 17:29 UTC, bathsundeep-graticule commented on .github/workflows/ghcr-ecr-republish.yml
> +      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
Yup, found this neat one here, lots more you can do: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion
```${parameter,,pattern}
This expansion modifies the case of alphabetic characters in parameter. The pattern is expanded to produce a pattern just as in filename expansion. Each character in the expanded value of parameter is tested against pattern, and, if it matches the pattern, its case is converted. The pattern should not attempt to match more than one character.

The ‘^’ operator converts lowercase letters matching pattern to uppercase; the ‘,’ operator converts matching uppercase letters to lowercase. The ‘^^’ and ‘,,’ expansions convert each matched character in the expanded value; the ‘^’ and ‘,’ expansions match and convert only the first character in the expanded value. If pattern is omitted, it is treated like a ‘?’, which matches every character.```

2023-12-01 21:32 UTC, mygzi approved these changes

2023-12-05 19:39 UTC, merged